package Desktop;
import controller.VehiclesOfInterestController;
import javax.swing.DefaultComboBoxModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yuan Tiezheng <tiezhengyuan@hotmail.com>
 */
public class addVehicleOfInterest extends javax.swing.JFrame {

    /**
     * Creates new form addVehicleOfInterest
     */
    public addVehicleOfInterest() {
        initComponents();
    }

    //
    public DefaultComboBoxModel reasonModel(){
        //retrieve reason
        VehiclesOfInterestController s= new VehiclesOfInterestController();
        String[] data = s.allReasonsForInterestKey();
        //
        DefaultComboBoxModel model = new DefaultComboBoxModel(data);
        return model;
    }
    //
    public DefaultComboBoxModel carMakeModel(){
        //retrieve reason
        VehiclesOfInterestController s= new VehiclesOfInterestController();
        String[] data = s.allVehicleMakeKey();
        //
        DefaultComboBoxModel model = new DefaultComboBoxModel(data);
        return model;
    }

        //
    public DefaultComboBoxModel carModelModel(){
        //retrieve reason
        VehiclesOfInterestController s= new VehiclesOfInterestController();
        String[] data = s.allVehicleModelKey();
        //
        DefaultComboBoxModel model = new DefaultComboBoxModel(data);
        return model;
    }
    
    //
    public boolean validateInput(){
        boolean tag=true;
        String licensePlate = jTextFieldPlate.getText();
        String year = jTextFieldYear.getText();
        String ownersPhone = jTextFieldPhone.getText();
        //
        if (licensePlate.isEmpty() ){
            jFrameEmptyPlate.setVisible(true);
            tag=false;
        }
        if (year.matches("[+-]?\\d*(\\.\\d+)?")==false){
            jFrameWrongYear.setVisible(true);
            tag=false;
        }
        return tag;
    }       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameEmptyPlate = new javax.swing.JFrame();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButtonClosePlate = new javax.swing.JButton();
        jFrameWrongYear = new javax.swing.JFrame();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButtonCloseYear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonConfirm = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jComboBoxReason = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPlate = new javax.swing.JTextField();
        jComboBoxMake = new javax.swing.JComboBox<>();
        jComboBoxModel = new javax.swing.JComboBox<>();
        jTextFieldColor = new javax.swing.JTextField();
        jTextFieldYear = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jFrameEmptyPlate.setMinimumSize(new java.awt.Dimension(400, 200));

        jLabel14.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 51));
        jLabel14.setText("Error!");

        jLabel15.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel15.setText("The liscense plate number is empty!");

        jButtonClosePlate.setText("Close");
        jButtonClosePlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClosePlateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrameEmptyPlateLayout = new javax.swing.GroupLayout(jFrameEmptyPlate.getContentPane());
        jFrameEmptyPlate.getContentPane().setLayout(jFrameEmptyPlateLayout);
        jFrameEmptyPlateLayout.setHorizontalGroup(
            jFrameEmptyPlateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameEmptyPlateLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jFrameEmptyPlateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameEmptyPlateLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameEmptyPlateLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addContainerGap())))
            .addGroup(jFrameEmptyPlateLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jButtonClosePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jFrameEmptyPlateLayout.setVerticalGroup(
            jFrameEmptyPlateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameEmptyPlateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jButtonClosePlate, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(56, 56, 56))
        );

        jFrameWrongYear.setMinimumSize(new java.awt.Dimension(400, 200));

        jLabel16.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 51));
        jLabel16.setText("Error!");

        jLabel17.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel17.setText("The liscense plate number is empty!");

        jButtonCloseYear.setText("Close");
        jButtonCloseYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseYearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrameWrongYearLayout = new javax.swing.GroupLayout(jFrameWrongYear.getContentPane());
        jFrameWrongYear.getContentPane().setLayout(jFrameWrongYearLayout);
        jFrameWrongYearLayout.setHorizontalGroup(
            jFrameWrongYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameWrongYearLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jFrameWrongYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameWrongYearLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameWrongYearLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addContainerGap())))
            .addGroup(jFrameWrongYearLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jButtonCloseYear, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jFrameWrongYearLayout.setVerticalGroup(
            jFrameWrongYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameWrongYearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jButtonCloseYear, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(56, 56, 56))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel1.setText("Add An Vehicle of Interest");

        jButtonConfirm.setText("Confirm");
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jComboBoxReason.setModel(reasonModel());

        jLabel2.setText("Reason for Interest");

        jLabel3.setText("Vehicle make");

        jLabel4.setText("Vehicle model");

        jLabel5.setText("License Plate");

        jComboBoxMake.setModel(carMakeModel());

        jComboBoxModel.setModel(carModelModel());

        jTextFieldYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldYearActionPerformed(evt);
            }
        });

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jLabel6.setText("Vehicle color");

        jLabel7.setText("Vehicle product year");

        jLabel8.setText("Owner name");

        jLabel9.setText("Owner phone number");

        jLabel10.setText("(Less than 10 numbers)");

        jLabel11.setText("(YYYY)");

        jLabel12.setText("(Less than 10 characters)");

        jLabel13.setText("(Last name + First name)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)))
                            .addComponent(jLabel8)
                            .addComponent(jButtonConfirm)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldPhone, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldYear, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldColor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxModel, javax.swing.GroupLayout.Alignment.LEADING, 0, 174, Short.MAX_VALUE)
                                .addComponent(jComboBoxMake, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxReason, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldPlate, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jButtonCancel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxReason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButtonConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldYearActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        // TODO add your handling code here:
        String licensePlate = jTextFieldPlate.getText();
        String year = jTextFieldYear.getText();
        String ownersPhone = jTextFieldPhone.getText();
        //
        if (licensePlate.isEmpty() ){
            System.out.printf(licensePlate);
            jFrameEmptyPlate.setVisible(true);
        }else if (year.matches("[+-]?\\d*(\\.\\d+)?")==false){
            jFrameWrongYear.setVisible(true);
        }
        else{
            String reason = jComboBoxReason.getSelectedItem().toString();
            String make  = jComboBoxMake.getSelectedItem().toString();
            String model = jComboBoxModel.getSelectedItem().toString();
            String color = jTextFieldColor.getText();
            String ownersName = jTextFieldName.getText();
            //update database
            VehiclesOfInterestController s= new VehiclesOfInterestController();
            s.createVehicleOfInterest(licensePlate, reason, make, model, year, color, ownersName, ownersPhone);
            //back to upper level UI
            this.dispose();
            headquarterTrackVehicle h =new headquarterTrackVehicle();
            h.show();
        }
    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void jButtonClosePlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClosePlateActionPerformed
        // TODO add your handling code here:
        jFrameEmptyPlate.setVisible(false);
    }//GEN-LAST:event_jButtonClosePlateActionPerformed

    private void jButtonCloseYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseYearActionPerformed
        // TODO add your handling code here:
        jFrameWrongYear.setVisible(false);
    }//GEN-LAST:event_jButtonCloseYearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addVehicleOfInterest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addVehicleOfInterest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addVehicleOfInterest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addVehicleOfInterest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addVehicleOfInterest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClosePlate;
    private javax.swing.JButton jButtonCloseYear;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JComboBox<String> jComboBoxMake;
    private javax.swing.JComboBox<String> jComboBoxModel;
    private javax.swing.JComboBox<String> jComboBoxReason;
    private javax.swing.JFrame jFrameEmptyPlate;
    private javax.swing.JFrame jFrameWrongYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldColor;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldPlate;
    private javax.swing.JTextField jTextFieldYear;
    // End of variables declaration//GEN-END:variables
}
